import { useState, useRef, useEffect } from 'react'
import { useNavigate, useParams, useLocation } from 'react-router-dom'
import {
  Sparkles, ArrowLeft, Code2, Eye, Rocket, Share2,
  RotateCcw, Download, Send, ChevronDown, Monitor,
  Tablet, Smartphone, X, Check, Loader2, Zap, Copy,
  MessageSquare, GitBranch, Play, Terminal, ChevronRight,
  Maximize2, Clock
} from 'lucide-react'

// ----- Real AI chat call -----
async function callAI(messages: { role: string; content: string }[], context: string) {
  const response = await fetch('/api/chat', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ messages, context }),
  })
  const data = await response.json()
  if (!response.ok) throw new Error(data.error || 'AI request failed')
  return data.content as string
}

// ----- Simulated generated code -----
function generateCode(prompt: string) {
  const name = prompt.split(' ').slice(0, 3).join(' ') || 'My App'
  return `import { useState } from 'react'

// ${name}
// Generated by Forge AI

export default function App() {
  const [count, setCount] = useState(0)
  const [todos, setTodos] = useState([
    { id: 1, text: 'Review designs', done: true },
    { id: 2, text: 'Build MVP', done: false },
    { id: 3, text: 'Write tests', done: false },
  ])
  const [input, setInput] = useState('')

  const addTodo = () => {
    if (!input.trim()) return
    setTodos(t => [...t, { id: Date.now(), text: input, done: false }])
    setInput('')
  }

  const toggleTodo = (id: number) => {
    setTodos(t => t.map(todo => todo.id === id ? { ...todo, done: !todo.done } : todo))
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-800 flex items-center justify-center p-6">
      <div className="w-full max-w-md bg-white/5 backdrop-blur border border-white/10 rounded-2xl p-6">
        <h1 className="text-2xl font-bold text-white mb-6">${name}</h1>

        <div className="flex gap-2 mb-6">
          <input
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && addTodo()}
            placeholder="Add a new item..."
            className="flex-1 bg-white/10 border border-white/10 rounded-lg px-4 py-2 text-white placeholder-white/40 outline-none focus:border-indigo-500"
          />
          <button
            onClick={addTodo}
            className="bg-indigo-600 hover:bg-indigo-500 text-white px-4 py-2 rounded-lg font-semibold transition-colors"
          >
            Add
          </button>
        </div>

        <div className="space-y-2">
          {todos.map(todo => (
            <div
              key={todo.id}
              onClick={() => toggleTodo(todo.id)}
              className="flex items-center gap-3 p-3 rounded-lg bg-white/5 hover:bg-white/10 cursor-pointer transition-colors group"
            >
              <div className={\`w-5 h-5 rounded-full border-2 flex items-center justify-center transition-colors \${todo.done ? 'bg-indigo-500 border-indigo-500' : 'border-white/30 group-hover:border-indigo-400'}\`}>
                {todo.done && <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>}
              </div>
              <span className={\`text-sm \${todo.done ? 'line-through text-white/40' : 'text-white'}\`}>{todo.text}</span>
            </div>
          ))}
        </div>

        <div className="mt-6 pt-4 border-t border-white/10 flex items-center justify-between text-xs text-white/40">
          <span>{todos.filter(t => t.done).length}/{todos.length} completed</span>
          <button
            onClick={() => setCount(c => c + 1)}
            className="text-indigo-400 hover:text-indigo-300"
          >
            Refreshed {count}×
          </button>
        </div>
      </div>
    </div>
  )
}`
}

// ----- Preview component -----
function AppPreview({ prompt }: { prompt: string }) {
  const appName = prompt.split(' ').slice(0, 4).join(' ') || 'My App'
  const [todos, setTodos] = useState([
    { id: 1, text: 'Review designs', done: true },
    { id: 2, text: 'Build MVP', done: false },
    { id: 3, text: 'Write tests', done: false },
  ])
  const [input, setInput] = useState('')

  const addTodo = () => {
    if (!input.trim()) return
    setTodos(t => [...t, { id: Date.now(), text: input, done: false }])
    setInput('')
  }

  const toggleTodo = (id: number) => {
    setTodos(t => t.map(todo => todo.id === id ? { ...todo, done: !todo.done } : todo))
  }

  return (
    <div style={{
      minHeight: '100%', background: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      padding: 24, fontFamily: 'Inter, sans-serif',
    }}>
      <div style={{
        width: '100%', maxWidth: 420,
        background: 'rgba(255,255,255,0.05)',
        backdropFilter: 'blur(20px)',
        border: '1px solid rgba(255,255,255,0.1)',
        borderRadius: 20, padding: 28,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 24 }}>
          <div style={{
            width: 36, height: 36, borderRadius: 10,
            background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Sparkles size={16} color="white" />
          </div>
          <h1 style={{ fontSize: 20, fontWeight: 800, color: 'white', margin: 0, letterSpacing: '-0.02em' }}>{appName}</h1>
        </div>

        <div style={{ display: 'flex', gap: 8, marginBottom: 20 }}>
          <input
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && addTodo()}
            placeholder="Add a new item..."
            style={{
              flex: 1, background: 'rgba(255,255,255,0.08)',
              border: '1px solid rgba(255,255,255,0.1)',
              borderRadius: 10, padding: '10px 14px',
              color: 'white', fontSize: 13, outline: 'none',
              fontFamily: 'inherit',
            }}
          />
          <button onClick={addTodo} style={{
            background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
            border: 'none', color: 'white',
            padding: '10px 18px', borderRadius: 10,
            fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit',
          }}>Add</button>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {todos.map(todo => (
            <div key={todo.id} onClick={() => toggleTodo(todo.id)} style={{
              display: 'flex', alignItems: 'center', gap: 12,
              padding: '12px 14px', borderRadius: 12,
              background: 'rgba(255,255,255,0.04)',
              border: '1px solid rgba(255,255,255,0.06)',
              cursor: 'pointer', transition: 'all 0.15s',
            }}
              onMouseEnter={e => e.currentTarget.style.background = 'rgba(255,255,255,0.08)'}
              onMouseLeave={e => e.currentTarget.style.background = 'rgba(255,255,255,0.04)'}
            >
              <div style={{
                width: 20, height: 20, borderRadius: '50%',
                border: `2px solid ${todo.done ? '#6366f1' : 'rgba(255,255,255,0.25)'}`,
                background: todo.done ? '#6366f1' : 'transparent',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                transition: 'all 0.15s', flexShrink: 0,
              }}>
                {todo.done && <Check size={11} color="white" strokeWidth={3} />}
              </div>
              <span style={{
                fontSize: 13, color: todo.done ? 'rgba(255,255,255,0.35)' : 'white',
                textDecoration: todo.done ? 'line-through' : 'none',
                transition: 'all 0.15s',
              }}>{todo.text}</span>
            </div>
          ))}
        </div>

        <div style={{
          marginTop: 20, paddingTop: 16,
          borderTop: '1px solid rgba(255,255,255,0.08)',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          fontSize: 12, color: 'rgba(255,255,255,0.35)',
        }}>
          <span>{todos.filter(t => t.done).length} of {todos.length} completed</span>
          <div style={{
            display: 'flex', alignItems: 'center', gap: 4,
            fontSize: 11, color: '#6366f1',
          }}>
            <Sparkles size={10} /> Powered by Forge
          </div>
        </div>
      </div>
    </div>
  )
}

// ----- Message types -----
type Message = {
  id: string
  role: 'user' | 'assistant'
  content: string
  timestamp: Date
  thinking?: boolean
}

// ----- Code editor (syntax-highlighted fake) -----
function CodePanel({ code }: { code: string }) {
  const [copied, setCopied] = useState(false)

  const copyCode = () => {
    navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const lines = code.split('\n')

  const colorize = (line: string) => {
    if (line.trim().startsWith('//')) return <span style={{ color: '#64748b' }}>{line}</span>
    if (line.trim().startsWith('import')) return <span><span style={{ color: '#c084fc' }}>import</span><span style={{ color: '#94a3b8' }}>{line.slice(6)}</span></span>
    if (line.includes('export default')) return <span><span style={{ color: '#c084fc' }}>export default </span><span style={{ color: '#818cf8' }}>function</span><span style={{ color: '#fbbf24' }}>{line.split('function')[1] || ''}</span></span>
    if (line.includes('const ') || line.includes('let ') || line.includes('var ')) {
      return <span><span style={{ color: '#818cf8' }}>{line.match(/\b(const|let|var)\b/)?.[0] || ''}</span><span style={{ color: '#94a3b8' }}>{line.replace(/\b(const|let|var)\b/, '')}</span></span>
    }
    if (line.trim().startsWith('return')) return <span><span style={{ color: '#c084fc' }}>return</span><span style={{ color: '#94a3b8' }}>{line.slice(line.indexOf('return') + 6)}</span></span>
    return <span style={{ color: '#94a3b8' }}>{line}</span>
  }

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column', background: '#0d0d14' }}>
      {/* Code toolbar */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '10px 16px', borderBottom: '1px solid rgba(99,102,241,0.1)',
        background: '#0a0a0f',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Terminal size={13} color="#6366f1" />
          <span style={{ fontSize: 12, color: '#64748b', fontFamily: 'monospace' }}>App.tsx</span>
          <div style={{
            background: 'rgba(99,102,241,0.1)', border: '1px solid rgba(99,102,241,0.2)',
            borderRadius: 4, padding: '1px 6px', fontSize: 10, color: '#818cf8',
          }}>TypeScript</div>
        </div>
        <button onClick={copyCode} style={{
          background: copied ? 'rgba(16,185,129,0.1)' : 'rgba(255,255,255,0.04)',
          border: `1px solid ${copied ? 'rgba(16,185,129,0.3)' : 'rgba(255,255,255,0.08)'}`,
          borderRadius: 6, padding: '4px 10px', cursor: 'pointer',
          display: 'flex', alignItems: 'center', gap: 6,
          fontSize: 11, color: copied ? '#10b981' : '#64748b', fontFamily: 'inherit',
          transition: 'all 0.2s',
        }}>
          {copied ? <><Check size={11} /> Copied!</> : <><Copy size={11} /> Copy</>}
        </button>
      </div>

      {/* Code */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '16px 0' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontFamily: 'monospace', fontSize: 12 }}>
          <tbody>
            {lines.map((line, i) => (
              <tr key={i} style={{ lineHeight: 1.7 }}>
                <td style={{ paddingLeft: 16, paddingRight: 16, color: '#374151', textAlign: 'right', userSelect: 'none', minWidth: 40, width: 40 }}>
                  {i + 1}
                </td>
                <td style={{ paddingRight: 20, whiteSpace: 'pre' }}>
                  {colorize(line)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// ===== Main Builder =====
export default function Builder() {
  const { projectId } = useParams<{ projectId: string }>()
  const navigate = useNavigate()
  const location = useLocation()
  const state = location.state as { prompt?: string; project?: { name: string } } | null

  const initialPrompt = state?.prompt || 'Build a task manager app'
  const projectName = state?.project?.name || initialPrompt.split(' ').slice(0, 4).join(' ')

  const [view, setView] = useState<'preview' | 'code'>('preview')
  const [viewport, setViewport] = useState<'desktop' | 'tablet' | 'mobile'>('desktop')
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '0',
      role: 'assistant',
      content: `I've built your app based on your description: "${initialPrompt}"\n\nThe app is live in the preview. You can:\n• Ask me to change colors, layout, or functionality\n• Add new features or sections\n• Modify any part of the UI\n\nWhat would you like to adjust?`,
      timestamp: new Date(),
    },
  ])
  const [input, setInput] = useState('')
  const [sending, setSending] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [code, setCode] = useState(() => generateCode(initialPrompt))
  const [deployed, setDeployed] = useState(false)
  const [deploying, setDeploying] = useState(false)
  const [shareMenu, setShareMenu] = useState(false)
  const [historyOpen, setHistoryOpen] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLTextAreaElement>(null)

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  const sendMessage = async () => {
    if (!input.trim() || sending) return
    const userMsg: Message = { id: Date.now().toString(), role: 'user', content: input, timestamp: new Date() }
    const thinkingMsg: Message = { id: (Date.now() + 1).toString(), role: 'assistant', content: '', timestamp: new Date(), thinking: true }
    setMessages(m => [...m, userMsg, thinkingMsg])
    const userInput = input
    setInput('')
    setSending(true)
    setGenerating(true)

    try {
      // Build conversation history (exclude thinking placeholders)
      const history = messages
        .filter(m => !m.thinking)
        .map(m => ({ role: m.role, content: m.content }))
      history.push({ role: 'user', content: userInput })

      const aiText = await callAI(history, initialPrompt)

      // Extract code block if Claude returned one
      const codeMatch = aiText.match(/```(?:tsx?|jsx?)\n([\s\S]*?)```/)
      if (codeMatch) {
        setCode(codeMatch[1].trim())
      }

      // Strip code block from chat message
      const displayText = aiText
        .replace(/```(?:tsx?|jsx?)\n[\s\S]*?```/g, '')
        .trim() || 'Done! Switch to the Code tab to see the updated component.'

      setMessages(m => m.map(msg =>
        msg.thinking ? { ...msg, content: displayText, thinking: false } : msg
      ))
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : 'Something went wrong. Check your API key in the .env file.'
      setMessages(m => m.map(msg =>
        msg.thinking ? { ...msg, content: `⚠️ ${errorMsg}`, thinking: false } : msg
      ))
    }

    setSending(false)
    setGenerating(false)
  }

  const handleDeploy = async () => {
    if (deploying || deployed) return
    setDeploying(true)
    await new Promise(r => setTimeout(r, 2000))
    setDeploying(false)
    setDeployed(true)
  }

  const viewportWidth = viewport === 'desktop' ? '100%' : viewport === 'tablet' ? '768px' : '375px'

  const SUGGESTIONS = [
    'Add dark/light mode toggle',
    'Change the color scheme to blue',
    'Add animations to the cards',
    'Make the layout responsive',
  ]

  return (
    <div style={{
      height: '100vh', background: '#0a0a0f', color: '#f1f5f9',
      display: 'flex', flexDirection: 'column', overflow: 'hidden',
    }}>
      {/* Top bar */}
      <header style={{
        height: 56, background: 'rgba(10,10,15,0.95)',
        borderBottom: '1px solid rgba(99,102,241,0.1)',
        display: 'flex', alignItems: 'center',
        padding: '0 16px', gap: 12, flexShrink: 0,
        backdropFilter: 'blur(20px)',
      }}>
        {/* Left */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, flex: 1 }}>
          <button onClick={() => navigate('/dashboard')} style={{
            background: 'rgba(255,255,255,0.04)',
            border: '1px solid rgba(255,255,255,0.07)',
            borderRadius: 8, width: 32, height: 32,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            cursor: 'pointer', color: '#64748b', transition: 'all 0.15s',
          }}
            onMouseEnter={e => { e.currentTarget.style.background = 'rgba(255,255,255,0.08)'; e.currentTarget.style.color = '#f1f5f9' }}
            onMouseLeave={e => { e.currentTarget.style.background = 'rgba(255,255,255,0.04)'; e.currentTarget.style.color = '#64748b' }}
          >
            <ArrowLeft size={15} />
          </button>

          <div style={{ width: 1, height: 20, background: 'rgba(99,102,241,0.15)' }} />

          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <div style={{
              width: 28, height: 28, borderRadius: 7,
              background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <Sparkles size={13} color="white" />
            </div>
            <div>
              <div style={{ fontSize: 13, fontWeight: 700, color: '#f1f5f9', lineHeight: 1.2 }}>{projectName}</div>
              <div style={{ fontSize: 10, color: '#475569', display: 'flex', alignItems: 'center', gap: 4 }}>
                <div style={{ width: 5, height: 5, borderRadius: '50%', background: generating ? '#f59e0b' : '#10b981' }} />
                {generating ? 'Generating...' : 'Ready'}
              </div>
            </div>
            <ChevronDown size={13} color="#475569" style={{ marginLeft: -2 }} />
          </div>
        </div>

        {/* Center — view toggle */}
        <div style={{
          display: 'flex', background: 'rgba(255,255,255,0.04)',
          border: '1px solid rgba(99,102,241,0.12)', borderRadius: 9,
          padding: 3, gap: 2,
        }}>
          {([
            { value: 'preview', icon: Eye, label: 'Preview' },
            { value: 'code', icon: Code2, label: 'Code' },
          ] as const).map(v => (
            <button key={v.value} onClick={() => setView(v.value)} style={{
              background: view === v.value ? 'rgba(99,102,241,0.15)' : 'transparent',
              border: view === v.value ? '1px solid rgba(99,102,241,0.25)' : '1px solid transparent',
              borderRadius: 6, padding: '5px 14px',
              display: 'flex', alignItems: 'center', gap: 6,
              fontSize: 12, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit',
              color: view === v.value ? '#818cf8' : '#64748b',
              transition: 'all 0.15s',
            }}>
              <v.icon size={13} /> {v.label}
            </button>
          ))}
        </div>

        {/* Right */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flex: 1, justifyContent: 'flex-end' }}>
          {/* Viewport */}
          <div style={{ display: 'flex', gap: 2 }}>
            {([
              { value: 'desktop', icon: Monitor },
              { value: 'tablet', icon: Tablet },
              { value: 'mobile', icon: Smartphone },
            ] as const).map(v => (
              <button key={v.value} onClick={() => setViewport(v.value)} style={{
                background: viewport === v.value ? 'rgba(99,102,241,0.12)' : 'transparent',
                border: `1px solid ${viewport === v.value ? 'rgba(99,102,241,0.25)' : 'transparent'}`,
                borderRadius: 6, width: 30, height: 30,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                cursor: 'pointer', color: viewport === v.value ? '#818cf8' : '#475569',
                transition: 'all 0.15s',
              }}>
                <v.icon size={13} />
              </button>
            ))}
          </div>

          <div style={{ width: 1, height: 20, background: 'rgba(99,102,241,0.1)' }} />

          {/* History */}
          <button onClick={() => setHistoryOpen(!historyOpen)} style={{
            background: 'rgba(255,255,255,0.04)',
            border: '1px solid rgba(255,255,255,0.07)',
            borderRadius: 8, padding: '6px 12px',
            display: 'flex', alignItems: 'center', gap: 6,
            fontSize: 12, fontWeight: 500, cursor: 'pointer',
            color: '#64748b', fontFamily: 'inherit', transition: 'all 0.15s',
          }}
            onMouseEnter={e => { e.currentTarget.style.background = 'rgba(255,255,255,0.07)'; e.currentTarget.style.color = '#94a3b8' }}
            onMouseLeave={e => { e.currentTarget.style.background = 'rgba(255,255,255,0.04)'; e.currentTarget.style.color = '#64748b' }}
          >
            <GitBranch size={12} /> History
          </button>

          {/* Share */}
          <div style={{ position: 'relative' }}>
            <button onClick={() => setShareMenu(!shareMenu)} style={{
              background: 'rgba(99,102,241,0.08)',
              border: '1px solid rgba(99,102,241,0.2)',
              borderRadius: 8, padding: '6px 12px',
              display: 'flex', alignItems: 'center', gap: 6,
              fontSize: 12, fontWeight: 600, cursor: 'pointer',
              color: '#818cf8', fontFamily: 'inherit', transition: 'all 0.15s',
            }}
              onMouseEnter={e => e.currentTarget.style.background = 'rgba(99,102,241,0.15)'}
              onMouseLeave={e => e.currentTarget.style.background = 'rgba(99,102,241,0.08)'}
            >
              <Share2 size={12} /> Share
            </button>
            {shareMenu && (
              <div style={{
                position: 'absolute', top: '100%', right: 0, marginTop: 8,
                background: '#1e1e2a', border: '1px solid rgba(99,102,241,0.2)',
                borderRadius: 12, padding: 12, minWidth: 260, zIndex: 200,
                boxShadow: '0 20px 60px rgba(0,0,0,0.5)',
              }}>
                <div style={{ fontSize: 12, color: '#64748b', marginBottom: 8 }}>Share link</div>
                <div style={{
                  display: 'flex', gap: 6, background: 'rgba(255,255,255,0.04)',
                  border: '1px solid rgba(99,102,241,0.15)',
                  borderRadius: 8, padding: '8px 10px', marginBottom: 8,
                }}>
                  <span style={{ fontSize: 11, color: '#94a3b8', flex: 1 }}>forge.app/preview/{projectId}</span>
                  <button onClick={() => setShareMenu(false)} style={{
                    background: 'rgba(99,102,241,0.15)', border: 'none',
                    borderRadius: 4, padding: '2px 8px', fontSize: 11,
                    color: '#818cf8', cursor: 'pointer', fontFamily: 'inherit',
                  }}>
                    Copy
                  </button>
                </div>
                <button onClick={() => setShareMenu(false)} style={{
                  width: '100%', background: 'transparent', border: 'none',
                  padding: 4, cursor: 'pointer', display: 'flex', justifyContent: 'flex-end',
                }}>
                  <X size={14} color="#475569" />
                </button>
              </div>
            )}
          </div>

          {/* Deploy */}
          <button onClick={handleDeploy} disabled={deploying} style={{
            background: deployed ? 'rgba(16,185,129,0.12)' : 'linear-gradient(135deg, #6366f1, #8b5cf6)',
            border: deployed ? '1px solid rgba(16,185,129,0.3)' : 'none',
            borderRadius: 8, padding: '6px 16px',
            display: 'flex', alignItems: 'center', gap: 6,
            fontSize: 12, fontWeight: 700, cursor: deploying ? 'not-allowed' : 'pointer',
            color: deployed ? '#10b981' : 'white', fontFamily: 'inherit',
            transition: 'all 0.2s', opacity: deploying ? 0.7 : 1,
          }}>
            {deploying ? (
              <><Loader2 size={12} style={{ animation: 'spin-slow 0.8s linear infinite' }} /> Deploying...</>
            ) : deployed ? (
              <><Check size={12} /> Deployed!</>
            ) : (
              <><Rocket size={12} /> Deploy</>
            )}
          </button>
        </div>
      </header>

      {/* Main layout */}
      <div style={{ flex: 1, display: 'grid', gridTemplateColumns: '360px 1fr', overflow: 'hidden' }}>
        {/* Chat panel */}
        <div style={{
          borderRight: '1px solid rgba(99,102,241,0.1)',
          display: 'flex', flexDirection: 'column',
          background: '#0d0d14', overflow: 'hidden',
        }}>
          {/* Chat header */}
          <div style={{
            padding: '14px 16px', borderBottom: '1px solid rgba(99,102,241,0.08)',
            display: 'flex', alignItems: 'center', gap: 10,
            background: 'rgba(10,10,15,0.5)',
          }}>
            <div style={{
              width: 28, height: 28, borderRadius: 7,
              background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <Sparkles size={13} color="white" />
            </div>
            <div>
              <div style={{ fontSize: 13, fontWeight: 700, color: '#f1f5f9' }}>Forge AI</div>
              <div style={{ fontSize: 10, color: '#475569' }}>Ask me to modify your app</div>
            </div>
            <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 5 }}>
              <div style={{ width: 6, height: 6, borderRadius: '50%', background: '#10b981' }} />
              <span style={{ fontSize: 10, color: '#10b981' }}>Online</span>
            </div>
          </div>

          {/* Messages */}
          <div style={{ flex: 1, overflowY: 'auto', padding: 16, display: 'flex', flexDirection: 'column', gap: 14 }}>
            {messages.map((msg) => (
              <div key={msg.id} style={{
                display: 'flex', flexDirection: 'column',
                alignItems: msg.role === 'user' ? 'flex-end' : 'flex-start',
                animation: 'slideInLeft 0.3s ease',
              }}>
                {msg.role === 'assistant' && (
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 6 }}>
                    <div style={{
                      width: 20, height: 20, borderRadius: 5,
                      background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                    }}>
                      <Sparkles size={10} color="white" />
                    </div>
                    <span style={{ fontSize: 11, fontWeight: 600, color: '#818cf8' }}>Forge</span>
                    <span style={{ fontSize: 10, color: '#374151' }}>
                      {msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>
                )}
                <div style={{
                  maxWidth: '88%',
                  background: msg.role === 'user'
                    ? 'linear-gradient(135deg, rgba(99,102,241,0.2), rgba(139,92,246,0.15))'
                    : 'rgba(255,255,255,0.04)',
                  border: `1px solid ${msg.role === 'user' ? 'rgba(99,102,241,0.3)' : 'rgba(255,255,255,0.07)'}`,
                  borderRadius: msg.role === 'user' ? '14px 14px 4px 14px' : '4px 14px 14px 14px',
                  padding: '10px 14px',
                  fontSize: 13, lineHeight: 1.65, color: msg.role === 'user' ? '#c7d2fe' : '#94a3b8',
                }}>
                  {msg.thinking ? (
                    <div style={{ display: 'flex', gap: 5, alignItems: 'center', padding: '2px 0' }}>
                      {[0, 0.2, 0.4].map((d, i) => (
                        <div key={i} style={{
                          width: 7, height: 7, borderRadius: '50%', background: '#6366f1',
                          animation: `pulse-ring 1.2s ${d}s ease-in-out infinite`,
                        }} />
                      ))}
                    </div>
                  ) : (
                    <span style={{ whiteSpace: 'pre-wrap' }}>{msg.content}</span>
                  )}
                </div>
                {msg.role === 'user' && (
                  <span style={{ fontSize: 10, color: '#374151', marginTop: 4 }}>
                    {msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </span>
                )}
              </div>
            ))}
            <div ref={messagesEndRef} />
          </div>

          {/* Suggestions */}
          {!sending && messages.length < 4 && (
            <div style={{ padding: '0 16px 12px', display: 'flex', flexDirection: 'column', gap: 6 }}>
              <div style={{ fontSize: 10, color: '#374151', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 2 }}>
                Suggestions
              </div>
              {SUGGESTIONS.map(s => (
                <button key={s} onClick={() => { setInput(s); inputRef.current?.focus() }} style={{
                  background: 'rgba(99,102,241,0.05)',
                  border: '1px solid rgba(99,102,241,0.12)',
                  borderRadius: 8, padding: '8px 12px',
                  fontSize: 12, color: '#64748b', cursor: 'pointer', fontFamily: 'inherit',
                  textAlign: 'left', display: 'flex', alignItems: 'center', gap: 8,
                  transition: 'all 0.15s',
                }}
                  onMouseEnter={e => { e.currentTarget.style.background = 'rgba(99,102,241,0.1)'; e.currentTarget.style.color = '#818cf8'; e.currentTarget.style.borderColor = 'rgba(99,102,241,0.25)' }}
                  onMouseLeave={e => { e.currentTarget.style.background = 'rgba(99,102,241,0.05)'; e.currentTarget.style.color = '#64748b'; e.currentTarget.style.borderColor = 'rgba(99,102,241,0.12)' }}
                >
                  <Zap size={11} color="#6366f1" />
                  {s}
                </button>
              ))}
            </div>
          )}

          {/* Input */}
          <div style={{
            padding: 12, borderTop: '1px solid rgba(99,102,241,0.08)',
            background: 'rgba(10,10,15,0.5)',
          }}>
            <div style={{
              background: 'rgba(255,255,255,0.03)',
              border: '1px solid rgba(99,102,241,0.18)',
              borderRadius: 12, padding: '10px 12px',
              display: 'flex', gap: 8, alignItems: 'flex-end',
            }}>
              <textarea
                ref={inputRef}
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={e => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault()
                    sendMessage()
                  }
                }}
                placeholder="Ask AI to modify your app..."
                rows={2}
                style={{
                  flex: 1, background: 'transparent', border: 'none', outline: 'none',
                  color: '#f1f5f9', fontSize: 13, resize: 'none',
                  fontFamily: 'inherit', lineHeight: 1.5, minHeight: 40,
                }}
              />
              <button onClick={sendMessage} disabled={sending || !input.trim()} style={{
                background: input.trim() && !sending ? 'linear-gradient(135deg, #6366f1, #8b5cf6)' : 'rgba(99,102,241,0.15)',
                border: 'none', borderRadius: 8, width: 32, height: 32,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                cursor: input.trim() && !sending ? 'pointer' : 'not-allowed',
                transition: 'all 0.15s', flexShrink: 0,
              }}>
                {sending ? <Loader2 size={13} color="white" style={{ animation: 'spin-slow 0.8s linear infinite' }} /> : <Send size={13} color="white" />}
              </button>
            </div>
            <div style={{ fontSize: 10, color: '#374151', marginTop: 6, display: 'flex', alignItems: 'center', gap: 4 }}>
              <MessageSquare size={9} />
              Press Enter to send, Shift+Enter for new line
            </div>
          </div>
        </div>

        {/* Preview / Code panel */}
        <div style={{ display: 'flex', flexDirection: 'column', overflow: 'hidden', background: view === 'code' ? '#0d0d14' : '#111118' }}>
          {/* Preview toolbar */}
          {view === 'preview' && (
            <div style={{
              height: 44, background: 'rgba(10,10,15,0.8)',
              borderBottom: '1px solid rgba(99,102,241,0.08)',
              display: 'flex', alignItems: 'center', padding: '0 16px', gap: 12,
            }}>
              <div style={{ display: 'flex', gap: 6 }}>
                {['#ff5f57', '#ffbd2e', '#28c840'].map((c, i) => (
                  <div key={i} style={{ width: 10, height: 10, borderRadius: '50%', background: c }} />
                ))}
              </div>
              <div style={{
                flex: 1, background: 'rgba(255,255,255,0.04)',
                border: '1px solid rgba(255,255,255,0.07)',
                borderRadius: 6, padding: '5px 14px',
                fontSize: 11, color: '#475569', maxWidth: 320, margin: '0 auto',
                textAlign: 'center',
              }}>
                forge.app/preview/{projectId}
              </div>
              <div style={{ display: 'flex', gap: 6 }}>
                <button style={{
                  background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.07)',
                  borderRadius: 6, width: 28, height: 28, cursor: 'pointer',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                }}>
                  <RotateCcw size={11} color="#475569" />
                </button>
                <button style={{
                  background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.07)',
                  borderRadius: 6, width: 28, height: 28, cursor: 'pointer',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                }}>
                  <Maximize2 size={11} color="#475569" />
                </button>
              </div>
            </div>
          )}

          {/* Content */}
          <div style={{
            flex: 1, overflow: 'auto',
            display: 'flex', justifyContent: view === 'preview' ? 'center' : 'stretch',
            background: view === 'preview' ? '#1a1a2e' : '#0d0d14',
          }}>
            {view === 'preview' ? (
              <div style={{
                width: viewportWidth, maxWidth: '100%',
                minHeight: '100%', transition: 'width 0.3s ease',
                boxShadow: viewport !== 'desktop' ? '0 0 60px rgba(0,0,0,0.5)' : 'none',
              }}>
                <AppPreview prompt={initialPrompt} />
              </div>
            ) : (
              <div style={{ width: '100%', height: '100%' }}>
                <CodePanel code={code} />
              </div>
            )}
          </div>

          {/* Bottom status bar */}
          <div style={{
            height: 32, background: 'rgba(10,10,15,0.8)',
            borderTop: '1px solid rgba(99,102,241,0.08)',
            display: 'flex', alignItems: 'center', padding: '0 16px',
            gap: 16, fontSize: 11, color: '#374151',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
              <div style={{ width: 5, height: 5, borderRadius: '50%', background: '#10b981' }} />
              <span>All systems operational</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
              <Play size={9} />
              <span>React 18 + TypeScript</span>
            </div>
            <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 4 }}>
              <Download size={9} />
              <span>Export code</span>
            </div>
            <div>
              <ChevronRight size={9} />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
              <Sparkles size={9} color="#6366f1" />
              <span style={{ color: '#6366f1' }}>Forge AI</span>
            </div>
          </div>
        </div>
      </div>

      {/* Version history drawer */}
      {historyOpen && (
        <div style={{
          position: 'fixed', inset: 0, zIndex: 300, display: 'flex', justifyContent: 'flex-end',
        }} onClick={() => setHistoryOpen(false)}>
          <div style={{
            width: 320, height: '100%',
            background: '#16161f', borderLeft: '1px solid rgba(99,102,241,0.15)',
            display: 'flex', flexDirection: 'column',
            boxShadow: '-20px 0 60px rgba(0,0,0,0.5)',
            animation: 'slideInRight 0.25s ease',
          }} onClick={e => e.stopPropagation()}>
            <div style={{ padding: '20px 20px 16px', borderBottom: '1px solid rgba(99,102,241,0.08)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div>
                <div style={{ fontSize: 14, fontWeight: 700, color: '#f1f5f9' }}>Version history</div>
                <div style={{ fontSize: 12, color: '#475569', marginTop: 2 }}>All saved versions</div>
              </div>
              <button onClick={() => setHistoryOpen(false)} style={{ background: 'transparent', border: 'none', cursor: 'pointer', padding: 4 }}>
                <X size={16} color="#475569" />
              </button>
            </div>
            <div style={{ flex: 1, overflowY: 'auto', padding: 16, display: 'flex', flexDirection: 'column', gap: 8 }}>
              {[
                { label: 'Current version', time: 'Just now', active: true },
                { label: 'Added dark mode', time: '10 min ago', active: false },
                { label: 'Changed layout', time: '25 min ago', active: false },
                { label: 'Initial build', time: '1 hour ago', active: false },
              ].map((v, i) => (
                <div key={i} style={{
                  background: v.active ? 'rgba(99,102,241,0.1)' : 'rgba(255,255,255,0.03)',
                  border: `1px solid ${v.active ? 'rgba(99,102,241,0.3)' : 'rgba(255,255,255,0.06)'}`,
                  borderRadius: 10, padding: '12px 14px', cursor: 'pointer',
                  transition: 'all 0.15s',
                }}
                  onMouseEnter={e => { if (!v.active) e.currentTarget.style.background = 'rgba(255,255,255,0.05)' }}
                  onMouseLeave={e => { if (!v.active) e.currentTarget.style.background = 'rgba(255,255,255,0.03)' }}
                >
                  <div style={{ fontSize: 13, fontWeight: 600, color: v.active ? '#818cf8' : '#94a3b8', marginBottom: 2 }}>{v.label}</div>
                  <div style={{ fontSize: 11, color: '#475569', display: 'flex', alignItems: 'center', gap: 4 }}>
                    <Clock size={10} />
                    {v.time}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
